version: '3.8'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:8080"

  admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
