using FC.Engine.Domain.Entities;
using FC.Engine.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FC.Engine.Infrastructure.Metadata.Configurations;

public class ConsentRecordConfiguration : IEntityTypeConfiguration<ConsentRecord>
{
    public void Configure(EntityTypeBuilder<ConsentRecord> builder)
    {
        builder.ToTable("consent_records");
        builder.HasKey(x => x.Id);
        builder.Property(x => x.TenantId).IsRequired();
        builder.Property(x => x.UserType).HasMaxLength(20).IsRequired();
        builder.Property(x => x.ConsentType).HasMaxLength(50).HasConversion<string>().IsRequired();
        builder.Property(x => x.PolicyVersion).HasMaxLength(20).IsRequired();
        builder.Property(x => x.ConsentMethod).HasMaxLength(30).IsRequired();
        builder.Property(x => x.IpAddress).HasMaxLength(45);
        builder.Property(x => x.UserAgent).HasMaxLength(500);
        builder.Property(x => x.ConsentedAt).HasDefaultValueSql("SYSUTCDATETIME()");

        builder.HasIndex(x => x.TenantId);
        builder.HasIndex(x => new { x.UserId, x.UserType, x.ConsentType });
        builder.HasIndex(x => new { x.TenantId, x.UserId, x.UserType, x.ConsentType, x.ConsentedAt });
    }
}

public class DataSubjectRequestConfiguration : IEntityTypeConfiguration<DataSubjectRequest>
{
    public void Configure(EntityTypeBuilder<DataSubjectRequest> builder)
    {
        builder.ToTable("data_subject_requests");
        builder.HasKey(x => x.Id);
        builder.Property(x => x.TenantId).IsRequired();
        builder.Property(x => x.RequestType).HasMaxLength(30).HasConversion<string>().IsRequired();
        builder.Property(x => x.RequestedByUserType).HasMaxLength(20).IsRequired();
        builder.Property(x => x.Status).HasMaxLength(20).HasConversion<string>().HasDefaultValue(DataSubjectRequestStatus.Received).IsRequired();
        builder.Property(x => x.Description).HasMaxLength(1000);
        builder.Property(x => x.DataPackagePath).HasMaxLength(500);
        builder.Property(x => x.CreatedAt).HasDefaultValueSql("SYSUTCDATETIME()");
        builder.Property(x => x.ResponseNotes).HasColumnType("nvarchar(max)");

        builder.HasIndex(x => x.TenantId);
        builder.HasIndex(x => new { x.TenantId, x.Status, x.DueDate });
        builder.HasIndex(x => new { x.TenantId, x.RequestType, x.CreatedAt });
    }
}

public class DataProcessingActivityConfiguration : IEntityTypeConfiguration<DataProcessingActivity>
{
    public void Configure(EntityTypeBuilder<DataProcessingActivity> builder)
    {
        builder.ToTable("data_processing_activities");
        builder.HasKey(x => x.Id);
        builder.Property(x => x.ModuleCode).HasMaxLength(30).IsRequired();
        builder.Property(x => x.ActivityName).HasMaxLength(200).IsRequired();
        builder.Property(x => x.Purpose).HasMaxLength(500).IsRequired();
        builder.Property(x => x.LegalBasis).HasMaxLength(100).IsRequired();
        builder.Property(x => x.DataCategories).HasColumnType("nvarchar(max)").IsRequired();
        builder.Property(x => x.DataSubjects).HasColumnType("nvarchar(max)").IsRequired();
        builder.Property(x => x.RetentionPeriod).HasMaxLength(100).IsRequired();
        builder.Property(x => x.ThirdPartySharing).HasColumnType("nvarchar(max)");
        builder.Property(x => x.SecurityMeasures).HasColumnType("nvarchar(max)").IsRequired();
        builder.Property(x => x.IsAutoGenerated).HasDefaultValue(true);
        builder.Property(x => x.LastUpdated).HasDefaultValueSql("SYSUTCDATETIME()");

        builder.HasIndex(x => new { x.ModuleCode, x.ActivityName }).IsUnique();
        builder.HasIndex(x => x.ModuleCode);
    }
}

public class DataBreachIncidentConfiguration : IEntityTypeConfiguration<DataBreachIncident>
{
    public void Configure(EntityTypeBuilder<DataBreachIncident> builder)
    {
        builder.ToTable("data_breach_incidents");
        builder.HasKey(x => x.Id);
        builder.Property(x => x.Severity).HasMaxLength(10).HasConversion<string>().IsRequired();
        builder.Property(x => x.Status).HasMaxLength(20).HasConversion<string>().HasDefaultValue(DataBreachStatus.Detected).IsRequired();
        builder.Property(x => x.Title).HasMaxLength(200).IsRequired();
        builder.Property(x => x.Description).HasColumnType("nvarchar(max)").IsRequired();
        builder.Property(x => x.DataCategoriesAffected).HasColumnType("nvarchar(max)");
        builder.Property(x => x.DpoNotes).HasColumnType("nvarchar(max)");
        builder.Property(x => x.CreatedAt).HasDefaultValueSql("SYSUTCDATETIME()");

        builder.HasIndex(x => x.TenantId);
        builder.HasIndex(x => new { x.Status, x.NitdaNotificationDeadline });
        builder.HasIndex(x => x.Severity);
    }
}
