namespace FC.Engine.Portal.Services;

/// <summary>
/// Static directory of all CBN-licensed financial institutions in Nigeria.
/// Source: https://www.cbn.gov.ng/supervision/finstitutions.html
/// </summary>
public static class CbnInstitutionDirectory
{
    public static readonly IReadOnlyList<(string Code, string Label)> Categories = new (string, string)[]
    {
        ("BDC", "Bureau de Change"),
        ("DFI", "Development Finance Institutions"),
        ("DH", "Discount Houses"),
        ("DMB", "Commercial Banks"),
        ("FC", "Finance Companies"),
        ("HC", "Holding Companies"),
        ("MB", "Merchant Banks"),
        ("MFB", "Micro-Finance Banks"),
        ("MMO", "Mobile Money Operators"),
        ("NIB", "Non-Interest Banks"),
        ("PMB", "Primary Mortgage Institutions"),
        ("PSB", "Payment Service Banks"),
    };

    private static readonly CbnInstitutionEntry[] _all =
    [
        // Bureau de Change (3)
        new("DULA GLOBAL BUREAU DE CHANGE LIMITED", "BDC", "Bureau de Change"),
        new("GREENVAULT BUREAU DE CHANGE LIMITED", "BDC", "Bureau de Change"),
        new("TRURATE GLOBAL BUREAU DE CHANGE LIMITED", "BDC", "Bureau de Change"),

        // Development Finance Institutions (8)
        new("Bank of Agriculture (BOA)", "DFI", "Development Finance Institutions"),
        new("BANK OF INDUSTRY", "DFI", "Development Finance Institutions"),
        new("Development Bank of Nigeria PLC", "DFI", "Development Finance Institutions"),
        new("FEDERAL MORTGAGE BANK OF NIGERIA", "DFI", "Development Finance Institutions"),
        new("NATIONAL CREDIT GUARANTEE COMPANY LIMITED", "DFI", "Development Finance Institutions"),
        new("NIGERIA EXPORT IMPORT BANK", "DFI", "Development Finance Institutions"),
        new("NIGERIAN CONSUMER CREDIT CORPORATION", "DFI", "Development Finance Institutions"),
        new("The Infrastructure Bank", "DFI", "Development Finance Institutions"),

        // Discount Houses (5)
        new("ASSOCIATED DISCOUNT HOUSE LTD.", "DH", "Discount Houses"),
        new("CONSOLIDATED DISCOUNT LIMITED", "DH", "Discount Houses"),
        new("EXPRESS DISCOUNT LIMITED", "DH", "Discount Houses"),
        new("FIRST SECURITIES DISCOUNT HOUSE LTD", "DH", "Discount Houses"),
        new("KAKAWA DISCOUNT HOUSE LTD", "DH", "Discount Houses"),

        // Commercial Banks (28)
        new("Access Bank Plc", "DMB", "Commercial Banks"),
        new("Alpha Morgan Bank Limited", "DMB", "Commercial Banks"),
        new("Citibank Nigeria Limited", "DMB", "Commercial Banks"),
        new("Ecobank Nigeria Plc", "DMB", "Commercial Banks"),
        new("Fidelity Bank Plc", "DMB", "Commercial Banks"),
        new("First Bank Nigeria Limited", "DMB", "Commercial Banks"),
        new("First City Monument Bank Plc", "DMB", "Commercial Banks"),
        new("Globus Bank Limited", "DMB", "Commercial Banks"),
        new("Guaranty Trust Bank Plc", "DMB", "Commercial Banks"),
        new("Keystone Bank Limited", "DMB", "Commercial Banks"),
        new("Nova Commercial Bank Limited", "DMB", "Commercial Banks"),
        new("Optimus Bank", "DMB", "Commercial Banks"),
        new("Parallex Bank Ltd", "DMB", "Commercial Banks"),
        new("Polaris Bank Plc", "DMB", "Commercial Banks"),
        new("Premium Trust Bank", "DMB", "Commercial Banks"),
        new("Providus Bank", "DMB", "Commercial Banks"),
        new("Signature Bank Limited", "DMB", "Commercial Banks"),
        new("Stanbic IBTC Bank Plc", "DMB", "Commercial Banks"),
        new("Standard Chartered Bank Nigeria Ltd.", "DMB", "Commercial Banks"),
        new("Sterling Bank Plc", "DMB", "Commercial Banks"),
        new("SunTrust Bank Nigeria Limited", "DMB", "Commercial Banks"),
        new("Tatum Bank Limited", "DMB", "Commercial Banks"),
        new("Titan Trust Bank Ltd", "DMB", "Commercial Banks"),
        new("Union Bank of Nigeria Plc", "DMB", "Commercial Banks"),
        new("United Bank For Africa Plc", "DMB", "Commercial Banks"),
        new("Unity Bank Plc", "DMB", "Commercial Banks"),
        new("Wema Bank Plc", "DMB", "Commercial Banks"),
        new("Zenith Bank Plc", "DMB", "Commercial Banks"),

        // Finance Companies (120)
        new("AAA FINANCE & INVESTMENT COMPANY LIMITED", "FC", "Finance Companies"),
        new("ADDOSSER FINANCE LIMITED", "FC", "Finance Companies"),
        new("AIQ CAPITAL FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("ALC FINANCE COMPANY LTD", "FC", "Finance Companies"),
        new("ALLIANZBRIDGE FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("AMS FINANCE & MANAGEMENT COMPANY LIMITED", "FC", "Finance Companies"),
        new("APICES FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("AQUILA LEASING LIMITED", "FC", "Finance Companies"),
        new("ARKERS FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("ASCESIA FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("BANCORP FINANCE LIMITED", "FC", "Finance Companies"),
        new("BERKSHIRE FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("BRANCH INTERNATIONAL FINANCIAL SERVICES LTD", "FC", "Finance Companies"),
        new("C & I LEASING PLC", "FC", "Finance Companies"),
        new("CANDOURCREST FINANCE LIMITED", "FC", "Finance Companies"),
        new("CAPITALFIELD FINANCIAL MANAGEMENT LIMITED", "FC", "Finance Companies"),
        new("CAPRI-MARTINS FINANCE LIMITED", "FC", "Finance Companies"),
        new("CARBON FINANCE AND INVESTMENT LIMITED", "FC", "Finance Companies"),
        new("CASH-LINK LEASING PLC", "FC", "Finance Companies"),
        new("CELOX FINANCE & INVESTMENT LIMITED", "FC", "Finance Companies"),
        new("Centrum Finance Company Limited", "FC", "Finance Companies"),
        new("CEVIANT FINANCE LIMITED", "FC", "Finance Companies"),
        new("CFS Financial Services Limited", "FC", "Finance Companies"),
        new("CITIHOMES FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("CO-LINK INVESTMENT MANAGEMENT COMPANY LIMITED", "FC", "Finance Companies"),
        new("CONSUMER INVESTMENT LIMITED", "FC", "Finance Companies"),
        new("CORE CAPITAL LIMITED", "FC", "Finance Companies"),
        new("COUNTY FINANCE LIMITED", "FC", "Finance Companies"),
        new("CREDIT DIRECT LIMITED", "FC", "Finance Companies"),
        new("CREDITE CAPITAL FINANCE & INVESTMENT LIMITED", "FC", "Finance Companies"),
        new("CREDITPRO FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("CROWNWISE FINANCE & INVESTMENTS PLC", "FC", "Finance Companies"),
        new("CRYSTAL FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("CS ADVANCE FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("DE-REAL PEOPLE FINANCE LIMITED", "FC", "Finance Companies"),
        new("DIGNITY FINANCE LIMITED", "FC", "Finance Companies"),
        new("DOMINION FINANCE LIMITED", "FC", "Finance Companies"),
        new("DYNAMIC FINANCE LIMITED", "FC", "Finance Companies"),
        new("E-FINANCE LIMITED", "FC", "Finance Companies"),
        new("ENCO FINANCE COMPANY LTD", "FC", "Finance Companies"),
        new("EVERDEN FINANCIAL SERVICES LTD", "FC", "Finance Companies"),
        new("EVIB FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("FACTORING & SUPPLY CHAIN FINANCE LIMITED", "FC", "Finance Companies"),
        new("FAST CREDIT LIMITED", "FC", "Finance Companies"),
        new("FEWCHORE FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("FIDUCIA FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("FINANCE AND COMMERCIAL SERVICES LIMITED", "FC", "Finance Companies"),
        new("FINANCIAL DERIVATIVES CO. LTD", "FC", "Finance Companies"),
        new("FIRST CORNERSTONE FINANCE AND INVESTMENT LIMITED", "FC", "Finance Companies"),
        new("FIRST MARINA TRUST LIMITED", "FC", "Finance Companies"),
        new("FLOBAL FINANCIAL SERVICES LIMITED", "FC", "Finance Companies"),
        new("FUNDIT FINANCIAL SERVICES LIMITED", "FC", "Finance Companies"),
        new("FUNDQUEST FINANCIAL SERVICES LIMITED", "FC", "Finance Companies"),
        new("FUNDSWORTH LIMITED", "FC", "Finance Companies"),
        new("GADOL FINANCE LTD", "FC", "Finance Companies"),
        new("GDL FINANCE AND LEASING COMPANY LIMITED", "FC", "Finance Companies"),
        new("GOODGATE FINANCE LTD", "FC", "Finance Companies"),
        new("GRAND TREASURERS LIMITED", "FC", "Finance Companies"),
        new("GREENBOND FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("GRIFFIN FINANCE LIMITED", "FC", "Finance Companies"),
        new("Harmony Breakthrough Finance Company Limited", "FC", "Finance Companies"),
        new("HIDDEKEL CAPITAL LTD", "FC", "Finance Companies"),
        new("INITIATIVE FINANCE LIMITED", "FC", "Finance Companies"),
        new("LECON FINANCIAL SERVICES COMPANY LIMITED", "FC", "Finance Companies"),
        new("LIGHT HOUSE INVESTMENTS LIMITED", "FC", "Finance Companies"),
        new("LUCIDUM FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("LUKEFIELD FINANCE LIMITED", "FC", "Finance Companies"),
        new("MERISTEM FINANCE LIMITED", "FC", "Finance Companies"),
        new("MEZCREDIT FINANCE LIMITED", "FC", "Finance Companies"),
        new("MIM FINANCE COMPANY LTD", "FC", "Finance Companies"),
        new("NEWEDGE FINANCE LIMITED", "FC", "Finance Companies"),
        new("NICHOLE FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("NOBLESERVE CAPITAL MANAGEMENT LIMITED", "FC", "Finance Companies"),
        new("NOLT FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("NORTHQUEST FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("O3 CAPITAL LIMITED", "FC", "Finance Companies"),
        new("OKAZI FINANCE LIMITED", "FC", "Finance Companies"),
        new("One-Stop Finance Company", "FC", "Finance Companies"),
        new("OPTICOM LEASING COMPANY LIMITED", "FC", "Finance Companies"),
        new("ORANGE ONE FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("OXYGEN X FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("PAGE INTERNATIONAL FINANCIAL SERVICES LIMITED", "FC", "Finance Companies"),
        new("PARADIGM FINANCE LIMITED", "FC", "Finance Companies"),
        new("PERENNIAL FINANCE LIMITED", "FC", "Finance Companies"),
        new("PFI FINANCIAL LIMITED", "FC", "Finance Companies"),
        new("PILOT FINANCE LIMITED", "FC", "Finance Companies"),
        new("PREFERRED FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("PROSPERIS FINNANCE LIMITED", "FC", "Finance Companies"),
        new("QUIDPRO FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("QUITS FINANCE LIMITED", "FC", "Finance Companies"),
        new("REDOAK TRUST AND INVESTMENT LIMITED", "FC", "Finance Companies"),
        new("RESOLUTION FINANCE LIMITED", "FC", "Finance Companies"),
        new("ROSABON FINANCIAL SERVICES LIMITED", "FC", "Finance Companies"),
        new("ROYAL CREST FINANCE LIMITED", "FC", "Finance Companies"),
        new("ROYAL EXCHANGE FINANCE AND INVESTMENT LIMITED", "FC", "Finance Companies"),
        new("SAGE GREY FINANCE LIMITED", "FC", "Finance Companies"),
        new("SFS CREDITS LIMITED", "FC", "Finance Companies"),
        new("SIMPLE FINANCE LIMTED", "FC", "Finance Companies"),
        new("SKYSTONE CAPITAL AND INVESTMENT LIMITED", "FC", "Finance Companies"),
        new("SNOW FINANCIAL SERVICES LIMITED", "FC", "Finance Companies"),
        new("SPRING SKY FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("STILL EARTH CAPITAL FINANCE LIMITED", "FC", "Finance Companies"),
        new("STIRLING TRUST COMPANY LIMITED", "FC", "Finance Companies"),
        new("SUPRA FINANCE LIMITED", "FC", "Finance Companies"),
        new("SYNC FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("TEKLA FACTROING AND FINANCE", "FC", "Finance Companies"),
        new("THE BROOK FINANCE LTD", "FC", "Finance Companies"),
        new("THOMAS GILTS FINANCE LIMITED", "FC", "Finance Companies"),
        new("TRANSKREDIT FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("TRINITY FINANCE LIMITED", "FC", "Finance Companies"),
        new("TROPICS FINANCE AND INVESTMENT COMPANY LIMITED", "FC", "Finance Companies"),
        new("UNIVERSAL INVEST & DEV. CO. LTD", "FC", "Finance Companies"),
        new("UT FINANCIAL SERVICES NIGERIA LIMITED", "FC", "Finance Companies"),
        new("VALE FINANCE LTD", "FC", "Finance Companies"),
        new("VIVA FINANCE LIMITED", "FC", "Finance Companies"),
        new("WESTWOOD FINANCIAL SERVICES LIMITED", "FC", "Finance Companies"),
        new("Whitecrust Finance Company Limited", "FC", "Finance Companies"),
        new("WOODHALL FINANCE COMPANY LIMITED", "FC", "Finance Companies"),
        new("WSTC FINANCIAL SERVICES LIMITED", "FC", "Finance Companies"),
        new("ZEDVANCE FINANCE LIMITED", "FC", "Finance Companies"),

        // Holding Companies (7)
        new("ACCESS HOLDINGS PLC", "HC", "Holding Companies"),
        new("FBN HOLDINGS PLC", "HC", "Holding Companies"),
        new("FCMB GROUP PLC", "HC", "Holding Companies"),
        new("FSDH HOLDING COMPANY", "HC", "Holding Companies"),
        new("GTB HOLD CO", "HC", "Holding Companies"),
        new("STANBIC IBTC HOLDINGS PLC", "HC", "Holding Companies"),
        new("STERLING FINANCIAL HOLDINGS LIMITED", "HC", "Holding Companies"),

        // Merchant Banks (5)
        new("CORONATION MERCHANT BANK", "MB", "Merchant Banks"),
        new("FBNQUEST MERCHANT BANK", "MB", "Merchant Banks"),
        new("FSDH MERCHANT BANK", "MB", "Merchant Banks"),
        new("GREENWICH MERCHANT BANK", "MB", "Merchant Banks"),
        new("RAND MERCHANT BANK", "MB", "Merchant Banks"),

        // Micro-Finance Banks (742)
        new("AACB Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("AB Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Abia SME Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Abia State University Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Abigi Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Above Only Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Abubakar Tafawa Balewa University (ATBU) Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Abucoop Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Abulesoro Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Accion Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("ACE Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Achina Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("ADA Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Adazi-Enu Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Adazi-Nnukwu Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Addosser Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Adeyemi College Staff Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Afekhafe Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Afemai Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Agosasa Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Ahmadu Bello University Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Aibio Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Ajewole Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Ajose Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Ajuta Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Akalabo Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Akokwa Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Akpo Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Aku Diewa Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Akuchukwu Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Al-Barakah Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Al-Hayat Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Albasu Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Alekun Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Alert Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Algreb Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Aliero Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("All Workers Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Alor Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Alpha Kapital Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Alvana Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("AMAC Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Amazu Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Amegy Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("AMJU-Unique Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("AMML Microfinance Bank Limited (Abuja Markets Management Ltd)", "MFB", "Micro-Finance Banks"),
        new("Ampersand Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Ample Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Amucha Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Anchorage Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Aniocha Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Annointed Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Aogo Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Apa Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Apex Trust Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Apple Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Aramoko Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Aris Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Asha Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Aspire Microfinance Bank LImited", "MFB", "Micro-Finance Banks"),
        new("Asset Matrix Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Assets Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Astra Polaris Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Auchi Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Auchi Polytechnic Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("AVE MARIA MFB", "MFB", "Micro-Finance Banks"),
        new("Avunegbe Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("AVVIC MICROFINANCE BANK LIMITED", "MFB", "Micro-Finance Banks"),
        new("Awe Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("AWESOME MFB", "MFB", "Micro-Finance Banks"),
        new("Awka-Etiti Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Awkuzu Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("AZSA Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("B C Kash Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Babba Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Babcock Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Babura Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("BAIGE MICROFINANCE BANK LIMITED", "MFB", "Micro-Finance Banks"),
        new("Baines Credit Microfinance bank", "MFB", "Micro-Finance Banks"),
        new("Balera Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Balogun Fulani Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Balogun Gambari Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Bam Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Banex Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Baobab Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Barnawa Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("BATAGWARA MFB", "MFB", "Micro-Finance Banks"),
        new("Bauchi CFA Mirofinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Bauchi Investment Corporation MFB Limited (BIC)", "MFB", "Micro-Finance Banks"),
        new("BAURE MFB", "MFB", "Micro-Finance Banks"),
        new("Bawyi Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Bayajidda Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Bayero University Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Bayetin Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Bejin-Doko Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Benue Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Benysta Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Berachah Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Best Star Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Bethel Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Better Life Microfinace Bank", "MFB", "Micro-Finance Banks"),
        new("Bichi Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("Bida Polytechnic Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("Blooms Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("BLUCON MFB", "MFB", "Micro-Finance Banks"),
        new("BLUE RIDGE MFB", "MFB", "Micro-Finance Banks"),
        new("BLUEPRINT INVESTMENTS MFB", "MFB", "Micro-Finance Banks"),
        new("BOCTRUST MFB", "MFB", "Micro-Finance Banks"),
        new("BOI MFB", "MFB", "Micro-Finance Banks"),
        new("BOJI BOJI MFB LTD.", "MFB", "Micro-Finance Banks"),
        new("BOKKOS MFB", "MFB", "Micro-Finance Banks"),
        new("BOMPAI MFB", "MFB", "Micro-Finance Banks"),
        new("BONGHE MFB", "MFB", "Micro-Finance Banks"),
        new("Boost Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("BORGU MFB", "MFB", "Micro-Finance Banks"),
        new("BORNO RENAISSANCE MFB LTD.", "MFB", "Micro-Finance Banks"),
        new("BOROMU MFB", "MFB", "Micro-Finance Banks"),
        new("BORSTAL MFB", "MFB", "Micro-Finance Banks"),
        new("BOSAK MFB", "MFB", "Micro-Finance Banks"),
        new("BOWEN MFB", "MFB", "Micro-Finance Banks"),
        new("BOWMAN MFB", "MFB", "Micro-Finance Banks"),
        new("BRETHREN  MFB", "MFB", "Micro-Finance Banks"),
        new("BRIGHTWAY MFB LTD", "MFB", "Micro-Finance Banks"),
        new("BROADVIEW MFB", "MFB", "Micro-Finance Banks"),
        new("BROOKS MFB", "MFB", "Micro-Finance Banks"),
        new("BUBAYERO MFB LTD", "MFB", "Micro-Finance Banks"),
        new("BUNDI MFB", "MFB", "Micro-Finance Banks"),
        new("BUNGUDU MFB", "MFB", "Micro-Finance Banks"),
        new("BUNKASA MFB", "MFB", "Micro-Finance Banks"),
        new("BUNKURE MFB", "MFB", "Micro-Finance Banks"),
        new("BUSU MFB", "MFB", "Micro-Finance Banks"),
        new("CANAAN MFB", "MFB", "Micro-Finance Banks"),
        new("CAPITALMETRIQ SWIFT MFB", "MFB", "Micro-Finance Banks"),
        new("CAPSTONE MFB", "MFB", "Micro-Finance Banks"),
        new("CARBON MFB", "MFB", "Micro-Finance Banks"),
        new("CARETAKER MFB", "MFB", "Micro-Finance Banks"),
        new("CASH RITE MFB", "MFB", "Micro-Finance Banks"),
        new("CASHA MICROFINANCE BANK", "MFB", "Micro-Finance Banks"),
        new("CASHCONNECT MFB", "MFB", "Micro-Finance Banks"),
        new("CASHWISE MICROFINANCE BANK LIMITED", "MFB", "Micro-Finance Banks"),
        new("CASTLE MFB", "MFB", "Micro-Finance Banks"),
        new("CATLAND MFB", "MFB", "Micro-Finance Banks"),
        new("CEDAR MFB", "MFB", "Micro-Finance Banks"),
        new("CHALLENGE MFB", "MFB", "Micro-Finance Banks"),
        new("CHANELLE MFB", "MFB", "Micro-Finance Banks"),
        new("CHANGAN RTS MFB", "MFB", "Micro-Finance Banks"),
        new("CHASE MFB LTD", "MFB", "Micro-Finance Banks"),
        new("CHEVRON EMPLOYEE CO-OPERATIVE MFB (CEMCS)", "MFB", "Micro-Finance Banks"),
        new("CHIBUEZE MFB", "MFB", "Micro-Finance Banks"),
        new("CHIKUM MFB", "MFB", "Micro-Finance Banks"),
        new("CHRISORE MFB", "MFB", "Micro-Finance Banks"),
        new("CHRONICLES MFB", "MFB", "Micro-Finance Banks"),
        new("CHUKWUNENYE MFB", "MFB", "Micro-Finance Banks"),
        new("CINTRUST MFB", "MFB", "Micro-Finance Banks"),
        new("CIT MFB", "MFB", "Micro-Finance Banks"),
        new("CITIZEN TRUST MFB", "MFB", "Micro-Finance Banks"),
        new("CITY MISSION METHODIST MFB", "MFB", "Micro-Finance Banks"),
        new("CIVIC MFB", "MFB", "Micro-Finance Banks"),
        new("CLOVERLEAF MFB", "MFB", "Micro-Finance Banks"),
        new("COAL CAMP MFB", "MFB", "Micro-Finance Banks"),
        new("COASTLINE MFB", "MFB", "Micro-Finance Banks"),
        new("COEMINNA MFB", "MFB", "Micro-Finance Banks"),
        new("CONFIDENCE MFB", "MFB", "Micro-Finance Banks"),
        new("CONSISTENT TRUST MFB", "MFB", "Micro-Finance Banks"),
        new("CONSUMER MFB", "MFB", "Micro-Finance Banks"),
        new("CORESTEP MFB", "MFB", "Micro-Finance Banks"),
        new("COVENANT MFB", "MFB", "Micro-Finance Banks"),
        new("CREEKLINE MFB", "MFB", "Micro-Finance Banks"),
        new("CRESCENT MFB", "MFB", "Micro-Finance Banks"),
        new("CREST MFB", "MFB", "Micro-Finance Banks"),
        new("CROSSRIVER MFB", "MFB", "Micro-Finance Banks"),
        new("CRUTECH MFB", "MFB", "Micro-Finance Banks"),
        new("CRYSTABEL MFB", "MFB", "Micro-Finance Banks"),
        new("CSD MFB", "MFB", "Micro-Finance Banks"),
        new("CUSTODIAN MFB", "MFB", "Micro-Finance Banks"),
        new("DAILY-TRUST MFB", "MFB", "Micro-Finance Banks"),
        new("DAL MFB", "MFB", "Micro-Finance Banks"),
        new("DAMBATTA- MAKODA MFB", "MFB", "Micro-Finance Banks"),
        new("DAVODANI MFB", "MFB", "Micro-Finance Banks"),
        new("DAWAKIN KUDU MFB", "MFB", "Micro-Finance Banks"),
        new("DAWAKIN TOFA MFB", "MFB", "Micro-Finance Banks"),
        new("DAYLIGHT MFB LTD", "MFB", "Micro-Finance Banks"),
        new("DEC-ENUGU MFB", "MFB", "Micro-Finance Banks"),
        new("DESTINY MFB", "MFB", "Micro-Finance Banks"),
        new("DIOBU MFB", "MFB", "Micro-Finance Banks"),
        new("DOGUWA MFB", "MFB", "Micro-Finance Banks"),
        new("DOLPHIN MFB", "MFB", "Micro-Finance Banks"),
        new("DORBEN MFB", "MFB", "Micro-Finance Banks"),
        new("DUTSE MFB", "MFB", "Micro-Finance Banks"),
        new("DUTSIN-MA MFB", "MFB", "Micro-Finance Banks"),
        new("e-BARCS MFB", "MFB", "Micro-Finance Banks"),
        new("EAGLE FLIGHT MFB", "MFB", "Micro-Finance Banks"),
        new("EARNWELL MFB", "MFB", "Micro-Finance Banks"),
        new("EAST GATE MFB", "MFB", "Micro-Finance Banks"),
        new("EASTMAN MFB", "MFB", "Micro-Finance Banks"),
        new("EASY ACCESS MFB LTD", "MFB", "Micro-Finance Banks"),
        new("EBEDI MFB", "MFB", "Micro-Finance Banks"),
        new("EBONYI STATE UNIVERSITY MFB (EBSU)", "MFB", "Micro-Finance Banks"),
        new("EDFIN MFB", "MFB", "Micro-Finance Banks"),
        new("EDO MFB", "MFB", "Micro-Finance Banks"),
        new("EGBE MFB", "MFB", "Micro-Finance Banks"),
        new("EGBEMOHA MFB", "MFB", "Micro-Finance Banks"),
        new("EGWAFIN MFB", "MFB", "Micro-Finance Banks"),
        new("EJINDU MFB", "MFB", "Micro-Finance Banks"),
        new("EK-RELIABLE MFB", "MFB", "Micro-Finance Banks"),
        new("EKIMOGUN MFB", "MFB", "Micro-Finance Banks"),
        new("EKONDO MFB", "MFB", "Micro-Finance Banks"),
        new("EKWULOBIA MFB", "MFB", "Micro-Finance Banks"),
        new("ELO-EMEDE MFB", "MFB", "Micro-Finance Banks"),
        new("EMERALD MFB", "MFB", "Micro-Finance Banks"),
        new("EMPIRE TRUST MFB", "MFB", "Micro-Finance Banks"),
        new("ENDWELL MFB", "MFB", "Micro-Finance Banks"),
        new("ENEDE MFB LTD", "MFB", "Micro-Finance Banks"),
        new("ENRICH MFB", "MFB", "Micro-Finance Banks"),
        new("EQUATOR MFB", "MFB", "Micro-Finance Banks"),
        new("EQUINOX MFB", "MFB", "Micro-Finance Banks"),
        new("ESO-E MFB", "MFB", "Micro-Finance Banks"),
        new("EVERGREEN MFB", "MFB", "Micro-Finance Banks"),
        new("EWT MFB", "MFB", "Micro-Finance Banks"),
        new("EXCEL MFB", "MFB", "Micro-Finance Banks"),
        new("EZEBO MFB", "MFB", "Micro-Finance Banks"),
        new("FAIDA MFB LTD", "MFB", "Micro-Finance Banks"),
        new("FAIRMONEY MFB LTD", "MFB", "Micro-Finance Banks"),
        new("FAME MFB", "MFB", "Micro-Finance Banks"),
        new("FAST MFB", "MFB", "Micro-Finance Banks"),
        new("FCMB MFB LTD.", "MFB", "Micro-Finance Banks"),
        new("FECETU MFB", "MFB", "Micro-Finance Banks"),
        new("FEDERAL POLYTECHNIC, NEKEDE MFB LTD", "MFB", "Micro-Finance Banks"),
        new("FEDETH CO-OP MFB", "MFB", "Micro-Finance Banks"),
        new("FEDPOLY NASARAWA MFB", "MFB", "Micro-Finance Banks"),
        new("FFS MFB", "MFB", "Micro-Finance Banks"),
        new("FIDFUND MFB", "MFB", "Micro-Finance Banks"),
        new("FIMS MFB", "MFB", "Micro-Finance Banks"),
        new("FINATRUST MFB", "MFB", "Micro-Finance Banks"),
        new("FINCA MFB", "MFB", "Micro-Finance Banks"),
        new("FINEX MFB", "MFB", "Micro-Finance Banks"),
        new("FIRMUS MFB", "MFB", "Micro-Finance Banks"),
        new("FIRST ACCESS MFB LTD", "MFB", "Micro-Finance Banks"),
        new("FIRST HERITAGE MFB", "MFB", "Micro-Finance Banks"),
        new("FIRST LOW-LAND MFB", "MFB", "Micro-Finance Banks"),
        new("FIRST MUTUAL MFB", "MFB", "Micro-Finance Banks"),
        new("FIRST OPTION MFB", "MFB", "Micro-Finance Banks"),
        new("FIRST ROYAL MFB", "MFB", "Micro-Finance Banks"),
        new("Flexi Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("FLOURISH MFB", "MFB", "Micro-Finance Banks"),
        new("FORESIGHT MFB", "MFB", "Micro-Finance Banks"),
        new("FORTRESS MFB", "MFB", "Micro-Finance Banks"),
        new("FORWARD MFB", "MFB", "Micro-Finance Banks"),
        new("FRONTLINE MFB", "MFB", "Micro-Finance Banks"),
        new("FTA FUNTUA MFB", "MFB", "Micro-Finance Banks"),
        new("FUD MFB", "MFB", "Micro-Finance Banks"),
        new("Fullrange Microfinance Bank Ltd", "MFB", "Micro-Finance Banks"),
        new("FUT MINNA", "MFB", "Micro-Finance Banks"),
        new("FUTO MFB", "MFB", "Micro-Finance Banks"),
        new("GAA AKANBI MFB", "MFB", "Micro-Finance Banks"),
        new("GABASAWA MFB", "MFB", "Micro-Finance Banks"),
        new("GAMAWA MFB", "MFB", "Micro-Finance Banks"),
        new("GAREWA MFB", "MFB", "Micro-Finance Banks"),
        new("GARKI MFB", "MFB", "Micro-Finance Banks"),
        new("GARU MALLAM MFB", "MFB", "Micro-Finance Banks"),
        new("GASHUA MFB", "MFB", "Micro-Finance Banks"),
        new("GAYA MFB", "MFB", "Micro-Finance Banks"),
        new("GBEDE MFB", "MFB", "Micro-Finance Banks"),
        new("GEZAWA MFB", "MFB", "Micro-Finance Banks"),
        new("GIANT STRIDE MFB LTD", "MFB", "Micro-Finance Banks"),
        new("Gidauniya Alheri MFB", "MFB", "Micro-Finance Banks"),
        new("GIGINYA MFB", "MFB", "Micro-Finance Banks"),
        new("GIREI MFB", "MFB", "Micro-Finance Banks"),
        new("GIWA MFB", "MFB", "Micro-Finance Banks"),
        new("GLOBAL INITIATIVE MFB", "MFB", "Micro-Finance Banks"),
        new("GLORY MFB", "MFB", "Micro-Finance Banks"),
        new("GMB MFB", "MFB", "Micro-Finance Banks"),
        new("GOBARAU MFB", "MFB", "Micro-Finance Banks"),
        new("GOLD MFB", "MFB", "Micro-Finance Banks"),
        new("GOLDEN CHOICE MFB", "MFB", "Micro-Finance Banks"),
        new("GOLDMAN MFB", "MFB", "Micro-Finance Banks"),
        new("GOMBE MFB", "MFB", "Micro-Finance Banks"),
        new("GOOD NEIGHBOURS MFB", "MFB", "Micro-Finance Banks"),
        new("GOOD NEWS MFB", "MFB", "Micro-Finance Banks"),
        new("GOOD SHEPHERD MFB", "MFB", "Micro-Finance Banks"),
        new("GOWANS MFB", "MFB", "Micro-Finance Banks"),
        new("GRANTS MFB", "MFB", "Micro-Finance Banks"),
        new("GRANULE MICROFINANCE BANK", "MFB", "Micro-Finance Banks"),
        new("GREEN ACRES MFB", "MFB", "Micro-Finance Banks"),
        new("GREEN ENERGY MFB", "MFB", "Micro-Finance Banks"),
        new("GREEN-BANK MFB", "MFB", "Micro-Finance Banks"),
        new("GREENVILLE MFB", "MFB", "Micro-Finance Banks"),
        new("GROOMING MFB", "MFB", "Micro-Finance Banks"),
        new("GTI MFB", "MFB", "Micro-Finance Banks"),
        new("GUDUSISA MFB", "MFB", "Micro-Finance Banks"),
        new("GULFARE MFB", "MFB", "Micro-Finance Banks"),
        new("GWONG MFB", "MFB", "Micro-Finance Banks"),
        new("HADEIJA MFB", "MFB", "Micro-Finance Banks"),
        new("HALAL CREDIT MFB", "MFB", "Micro-Finance Banks"),
        new("HALLOWED MFB", "MFB", "Micro-Finance Banks"),
        new("HAMADA MFB", "MFB", "Micro-Finance Banks"),
        new("HAMDA MFB", "MFB", "Micro-Finance Banks"),
        new("HASAL MFB", "MFB", "Micro-Finance Banks"),
        new("HEADWAY MFB LTD", "MFB", "Micro-Finance Banks"),
        new("HEDGE MICROFINANCE BANK LIMITED", "MFB", "Micro-Finance Banks"),
        new("HIGHLAND MFB", "MFB", "Micro-Finance Banks"),
        new("HINACHE MFB", "MFB", "Micro-Finance Banks"),
        new("HONEY MFB", "MFB", "Micro-Finance Banks"),
        new("HOPE ALIVE MFB", "MFB", "Micro-Finance Banks"),
        new("I-Care Microfinance Bank Ltd", "MFB", "Micro-Finance Banks"),
        new("IBETO MFB", "MFB", "Micro-Finance Banks"),
        new("IBILE MFB", "MFB", "Micro-Finance Banks"),
        new("IBOLO MFB", "MFB", "Micro-Finance Banks"),
        new("IBOM FADAMA MFB", "MFB", "Micro-Finance Banks"),
        new("IBRAHIM BADAMASI BABANGIDA UNIVERSITY  MFB", "MFB", "Micro-Finance Banks"),
        new("IBU-AJE MFB", "MFB", "Micro-Finance Banks"),
        new("ICHI MFB", "MFB", "Micro-Finance Banks"),
        new("IDEATO MFB", "MFB", "Micro-Finance Banks"),
        new("IDEMILI MFB", "MFB", "Micro-Finance Banks"),
        new("IFEDAPO MFB", "MFB", "Micro-Finance Banks"),
        new("IFELODUN MFB", "MFB", "Micro-Finance Banks"),
        new("IGBO-UKWU MFB", "MFB", "Micro-Finance Banks"),
        new("IGBOORA MFB", "MFB", "Micro-Finance Banks"),
        new("IHIALA MFB", "MFB", "Micro-Finance Banks"),
        new("IJARE MFB", "MFB", "Micro-Finance Banks"),
        new("IJEBU IFE MFB", "MFB", "Micro-Finance Banks"),
        new("IKENNE MFB", "MFB", "Micro-Finance Banks"),
        new("IKIRE MFB", "MFB", "Micro-Finance Banks"),
        new("IKORODU DIVISION MFB", "MFB", "Micro-Finance Banks"),
        new("IKOYI-ILE MFB", "MFB", "Micro-Finance Banks"),
        new("IKOYI-OSUN MFB", "MFB", "Micro-Finance Banks"),
        new("ILARO POLYTECHNIC MFB", "MFB", "Micro-Finance Banks"),
        new("ILE-OLUJI MFB", "MFB", "Micro-Finance Banks"),
        new("ILISAN MFB", "MFB", "Micro-Finance Banks"),
        new("ILOBU MFB", "MFB", "Micro-Finance Banks"),
        new("ILOFFA MFB", "MFB", "Micro-Finance Banks"),
        new("ILORA MFB", "MFB", "Micro-Finance Banks"),
        new("ILORIN MFB", "MFB", "Micro-Finance Banks"),
        new("ILUDUN ORO MFB", "MFB", "Micro-Finance Banks"),
        new("ILUTUNTUN-OSORO MFB", "MFB", "Micro-Finance Banks"),
        new("IMO STATE MICROFINANCE BANK", "MFB", "Micro-Finance Banks"),
        new("IMODI-IMOSAN MFB", "MFB", "Micro-Finance Banks"),
        new("IMOPOLY MFB", "MFB", "Micro-Finance Banks"),
        new("IMOWO MFB", "MFB", "Micro-Finance Banks"),
        new("IMSU MFB", "MFB", "Micro-Finance Banks"),
        new("IMT MFB", "MFB", "Micro-Finance Banks"),
        new("INFINITY MFB", "MFB", "Micro-Finance Banks"),
        new("INSIGHT MFB", "MFB", "Micro-Finance Banks"),
        new("IPAPO MFB", "MFB", "Micro-Finance Banks"),
        new("IPERU MFB", "MFB", "Micro-Finance Banks"),
        new("IRL MFB", "MFB", "Micro-Finance Banks"),
        new("ISALE OYO MFB", "MFB", "Micro-Finance Banks"),
        new("ISHIAGU MFB", "MFB", "Micro-Finance Banks"),
        new("ISHIE MFB", "MFB", "Micro-Finance Banks"),
        new("ISI-UZO MFB", "MFB", "Micro-Finance Banks"),
        new("ISLAND MFB", "MFB", "Micro-Finance Banks"),
        new("ISUA MFB", "MFB", "Micro-Finance Banks"),
        new("ISUOFIA MFB", "MFB", "Micro-Finance Banks"),
        new("IWA MFB", "MFB", "Micro-Finance Banks"),
        new("IWADE MFB", "MFB", "Micro-Finance Banks"),
        new("IWOYE-IJESA MFB", "MFB", "Micro-Finance Banks"),
        new("IYA-ZAKARI (MASHI) MFB", "MFB", "Micro-Finance Banks"),
        new("IYAMOYE MFB", "MFB", "Micro-Finance Banks"),
        new("IYERU OKIN MFB", "MFB", "Micro-Finance Banks"),
        new("IYIN EKITI MFB", "MFB", "Micro-Finance Banks"),
        new("IZON MFB LTD", "MFB", "Micro-Finance Banks"),
        new("JANMAA MFB", "MFB", "Micro-Finance Banks"),
        new("JANZAMA MFB", "MFB", "Micro-Finance Banks"),
        new("JEN MFB", "MFB", "Micro-Finance Banks"),
        new("JESSEFIELD MFB", "MFB", "Micro-Finance Banks"),
        new("JEWEL COOP MFB", "MFB", "Micro-Finance Banks"),
        new("KABO MFB", "MFB", "Micro-Finance Banks"),
        new("KADPOLY MFB", "MFB", "Micro-Finance Banks"),
        new("KADUPE MFB", "MFB", "Micro-Finance Banks"),
        new("KAMBA MFB", "MFB", "Micro-Finance Banks"),
        new("KANKARA MFB", "MFB", "Micro-Finance Banks"),
        new("KANKIA MFB LTD", "MFB", "Micro-Finance Banks"),
        new("KANO POLY MFB", "MFB", "Micro-Finance Banks"),
        new("KANO-WEST MFB", "MFB", "Micro-Finance Banks"),
        new("KATAGUM MFB", "MFB", "Micro-Finance Banks"),
        new("KAYVEE MFB", "MFB", "Micro-Finance Banks"),
        new("KC MFB", "MFB", "Micro-Finance Banks"),
        new("KCMB MFB", "MFB", "Micro-Finance Banks"),
        new("KENECHUKWU MFB", "MFB", "Micro-Finance Banks"),
        new("KHB MFB", "MFB", "Micro-Finance Banks"),
        new("KINGDOM COLLEGE MFB LTD", "MFB", "Micro-Finance Banks"),
        new("KISI MFB", "MFB", "Micro-Finance Banks"),
        new("KKU Microfinance", "MFB", "Micro-Finance Banks"),
        new("KMC MFB", "MFB", "Micro-Finance Banks"),
        new("KONTAGORA MFB", "MFB", "Micro-Finance Banks"),
        new("KOPO-KOPE MFB", "MFB", "Micro-Finance Banks"),
        new("KREDI MONEY MFB (Formerly CONPRO MFB)", "MFB", "Micro-Finance Banks"),
        new("KUDA MFB", "MFB", "Micro-Finance Banks"),
        new("KUMBOTSO MFB", "MFB", "Micro-Finance Banks"),
        new("KUNAGABA MFB", "MFB", "Micro-Finance Banks"),
        new("KUNCHI MFB", "MFB", "Micro-Finance Banks"),
        new("KURA MFB", "MFB", "Micro-Finance Banks"),
        new("KUSALLA MFB", "MFB", "Micro-Finance Banks"),
        new("KWACOFOCUS MFB", "MFB", "Micro-Finance Banks"),
        new("KWARA POLYTECHNIC MICROFINANCE BANK LIMITED", "MFB", "Micro-Finance Banks"),
        new("KWASU MFB", "MFB", "Micro-Finance Banks"),
        new("KWATASHI MFB", "MFB", "Micro-Finance Banks"),
        new("LA FAYETTE MFB", "MFB", "Micro-Finance Banks"),
        new("Ladder Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("LANDGOLD MFB", "MFB", "Micro-Finance Banks"),
        new("LAPO MFB", "MFB", "Micro-Finance Banks"),
        new("LAVENDER", "MFB", "Micro-Finance Banks"),
        new("LAWYERS MFB", "MFB", "Micro-Finance Banks"),
        new("LAYELU MFB", "MFB", "Micro-Finance Banks"),
        new("LEADCITY MFB", "MFB", "Micro-Finance Banks"),
        new("LEGACY MFB", "MFB", "Micro-Finance Banks"),
        new("LEGEND MFB", "MFB", "Micro-Finance Banks"),
        new("LETSHEGO MFB", "MFB", "Micro-Finance Banks"),
        new("LEVITE MFB", "MFB", "Micro-Finance Banks"),
        new("LIFEGATE MFB", "MFB", "Micro-Finance Banks"),
        new("LIGHT MFB", "MFB", "Micro-Finance Banks"),
        new("LINKS MFB", "MFB", "Micro-Finance Banks"),
        new("LIVING SPRING MFB", "MFB", "Micro-Finance Banks"),
        new("LOBREM MFB", "MFB", "Micro-Finance Banks"),
        new("LOVONUS MFB", "MFB", "Micro-Finance Banks"),
        new("M & M MFB", "MFB", "Micro-Finance Banks"),
        new("MAB ALLIANZ MFB LTD", "MFB", "Micro-Finance Banks"),
        new("MACROD MFB", "MFB", "Micro-Finance Banks"),
        new("MADELYN MFB", "MFB", "Micro-Finance Banks"),
        new("MADOBI MFB", "MFB", "Micro-Finance Banks"),
        new("MAGAJIN-GIRI MFB", "MFB", "Micro-Finance Banks"),
        new("MAGNET MFB", "MFB", "Micro-Finance Banks"),
        new("MAIGATARI MFB", "MFB", "Micro-Finance Banks"),
        new("MAIN TRUST MFB", "MFB", "Micro-Finance Banks"),
        new("MAINLAND MFB", "MFB", "Micro-Finance Banks"),
        new("MAINSTREET MFB", "MFB", "Micro-Finance Banks"),
        new("MALACHY MFB", "MFB", "Micro-Finance Banks"),
        new("MAPOLY MFB", "MFB", "Micro-Finance Banks"),
        new("MARITIME MFB", "MFB", "Micro-Finance Banks"),
        new("MATAZU MFB LTD", "MFB", "Micro-Finance Banks"),
        new("MAXITRUST MFB", "MFB", "Micro-Finance Banks"),
        new("MAYDEN MICROFINANCE BANK", "MFB", "Micro-Finance Banks"),
        new("MBAITOLI MFB", "MFB", "Micro-Finance Banks"),
        new("MBAWULU MFB", "MFB", "Micro-Finance Banks"),
        new("MEGA MFB", "MFB", "Micro-Finance Banks"),
        new("MEGAPRAISE MFB", "MFB", "Micro-Finance Banks"),
        new("MEMENTO MFB LTD", "MFB", "Micro-Finance Banks"),
        new("MEMPHIS MICROFINANCE BANK LIMITED", "MFB", "Micro-Finance Banks"),
        new("MERCHANT MFB", "MFB", "Micro-Finance Banks"),
        new("MERIDIAN MFB", "MFB", "Micro-Finance Banks"),
        new("MGBIDI MFB", "MFB", "Micro-Finance Banks"),
        new("MICHEAL OKPARA UNIVERSITY MFB", "MFB", "Micro-Finance Banks"),
        new("MICROVIS MFB", "MFB", "Micro-Finance Banks"),
        new("MIDLAND MFB", "MFB", "Micro-Finance Banks"),
        new("MINJI-SE CHURCHILL MFB", "MFB", "Micro-Finance Banks"),
        new("MINJIBIR MFB", "MFB", "Micro-Finance Banks"),
        new("MKOBO MFB LTD", "MFB", "Micro-Finance Banks"),
        new("MODEL MFB", "MFB", "Micro-Finance Banks"),
        new("MODIYA YEKOKPE MFB", "MFB", "Micro-Finance Banks"),
        new("MOLUSI MFB", "MFB", "Micro-Finance Banks"),
        new("MONARCH MFB", "MFB", "Micro-Finance Banks"),
        new("MONEYTRONICS MFB (Formerly Ipodo-Ikeja MFB)", "MFB", "Micro-Finance Banks"),
        new("Moneytrust MFB", "MFB", "Micro-Finance Banks"),
        new("MOYOFADE MFB", "MFB", "Micro-Finance Banks"),
        new("MOZFIN MFB", "MFB", "Micro-Finance Banks"),
        new("MULTIVEST MFB", "MFB", "Micro-Finance Banks"),
        new("MUTUAL BENEFIT MFB", "MFB", "Micro-Finance Banks"),
        new("MUTUAL TRUST MFB", "MFB", "Micro-Finance Banks"),
        new("MWAGHAVUL MFB", "MFB", "Micro-Finance Banks"),
        new("NAGARTA MFB", "MFB", "Micro-Finance Banks"),
        new("NAISA MFB", "MFB", "Micro-Finance Banks"),
        new("NAKOWA MFB", "MFB", "Micro-Finance Banks"),
        new("NAMODA MFB", "MFB", "Micro-Finance Banks"),
        new("NASARAWA MFB", "MFB", "Micro-Finance Banks"),
        new("NDIOLU MFB", "MFB", "Micro-Finance Banks"),
        new("NDIORAH MFB", "MFB", "Micro-Finance Banks"),
        new("NENZIT MFB", "MFB", "Micro-Finance Banks"),
        new("NEPTUNE MFB", "MFB", "Micro-Finance Banks"),
        new("NEW DAWN MFB", "MFB", "Micro-Finance Banks"),
        new("NEW ERA MFB", "MFB", "Micro-Finance Banks"),
        new("NEW GOLDEN PASTURES MFB", "MFB", "Micro-Finance Banks"),
        new("NEW WOMEN'S MFB", "MFB", "Micro-Finance Banks"),
        new("NGBO MFB LTD", "MFB", "Micro-Finance Banks"),
        new("NICE MFB", "MFB", "Micro-Finance Banks"),
        new("NIGERIAN NAVY MFB LTD", "MFB", "Micro-Finance Banks"),
        new("NIGERIAN PRISONS MFB", "MFB", "Micro-Finance Banks"),
        new("NINGI MFB", "MFB", "Micro-Finance Banks"),
        new("NIRSAL MFB", "MFB", "Micro-Finance Banks"),
        new("NKPA MFB", "MFB", "Micro-Finance Banks"),
        new("NKPOLOGWU MFB", "MFB", "Micro-Finance Banks"),
        new("NKPOLU-UST MFB", "MFB", "Micro-Finance Banks"),
        new("NNOKWA MFB", "MFB", "Micro-Finance Banks"),
        new("NOBLE MFB", "MFB", "Micro-Finance Banks"),
        new("NOMASE MICROFINANCE BANK LTD", "MFB", "Micro-Finance Banks"),
        new("NOUN MFB", "MFB", "Micro-Finance Banks"),
        new("NOVEL MFB", "MFB", "Micro-Finance Banks"),
        new("NPF MFB", "MFB", "Micro-Finance Banks"),
        new("NRI MFB", "MFB", "Micro-Finance Banks"),
        new("NSU MFB", "MFB", "Micro-Finance Banks"),
        new("NSUK MFB", "MFB", "Micro-Finance Banks"),
        new("NSUKKA TOWNSHIP MFB", "MFB", "Micro-Finance Banks"),
        new("NUGGETS MFB", "MFB", "Micro-Finance Banks"),
        new("NUMO MFB", "MFB", "Micro-Finance Banks"),
        new("NUN MFB", "MFB", "Micro-Finance Banks"),
        new("NUT OKEBOLA MFB", "MFB", "Micro-Finance Banks"),
        new("NWANNEGADI MFB", "MFB", "Micro-Finance Banks"),
        new("OAKLAND MFB", "MFB", "Micro-Finance Banks"),
        new("OBA MFB", "MFB", "Micro-Finance Banks"),
        new("OBAFEMI AWOLOWO UNIVERSITY MFB", "MFB", "Micro-Finance Banks"),
        new("OBELEDU MFB", "MFB", "Micro-Finance Banks"),
        new("OBODOUKWU MFB", "MFB", "Micro-Finance Banks"),
        new("OBOKUN MFB", "MFB", "Micro-Finance Banks"),
        new("OBOLLO MFB", "MFB", "Micro-Finance Banks"),
        new("OCHE MFB", "MFB", "Micro-Finance Banks"),
        new("OCON SUCCESS MFB", "MFB", "Micro-Finance Banks"),
        new("OCTOPUS MFB", "MFB", "Micro-Finance Banks"),
        new("ODOAKPU MFB", "MFB", "Micro-Finance Banks"),
        new("ODU MFB", "MFB", "Micro-Finance Banks"),
        new("OGBERURU MFB", "MFB", "Micro-Finance Banks"),
        new("OGBETE MFB", "MFB", "Micro-Finance Banks"),
        new("OGBOEFERE MFB", "MFB", "Micro-Finance Banks"),
        new("OGIGE MFB", "MFB", "Micro-Finance Banks"),
        new("OGIYAN MFB", "MFB", "Micro-Finance Banks"),
        new("OHAFIA MFB", "MFB", "Micro-Finance Banks"),
        new("OHHA MFB", "MFB", "Micro-Finance Banks"),
        new("OJOKORO MFB", "MFB", "Micro-Finance Banks"),
        new("OKE- ARO OREDEGBE MFB", "MFB", "Micro-Finance Banks"),
        new("OKEAGBE MFB", "MFB", "Micro-Finance Banks"),
        new("OKENGWE MFB", "MFB", "Micro-Finance Banks"),
        new("OKO MFB", "MFB", "Micro-Finance Banks"),
        new("OKPE MFB", "MFB", "Micro-Finance Banks"),
        new("OKPOFE MFB", "MFB", "Micro-Finance Banks"),
        new("OKPOGA MFB", "MFB", "Micro-Finance Banks"),
        new("OKUKU MFB", "MFB", "Micro-Finance Banks"),
        new("OKUTA MFB", "MFB", "Micro-Finance Banks"),
        new("OKWO-OHA MFB", "MFB", "Micro-Finance Banks"),
        new("OLABISI ONABANJO UNIVERSITY MFB", "MFB", "Micro-Finance Banks"),
        new("OLIVE MFB", "MFB", "Micro-Finance Banks"),
        new("OLOWOLAGBA MFB", "MFB", "Micro-Finance Banks"),
        new("OLU-BASIRI MFB", "MFB", "Micro-Finance Banks"),
        new("OLUCHUKWU MFB", "MFB", "Micro-Finance Banks"),
        new("OMAK MFB", "MFB", "Micro-Finance Banks"),
        new("OMIYE MFB", "MFB", "Micro-Finance Banks"),
        new("OMUMA MFB", "MFB", "Micro-Finance Banks"),
        new("ONIBU-ORE MFB", "MFB", "Micro-Finance Banks"),
        new("ORAUKWU MFB", "MFB", "Micro-Finance Banks"),
        new("ORILONISE MFB", "MFB", "Micro-Finance Banks"),
        new("ORISUN MFB", "MFB", "Micro-Finance Banks"),
        new("ORITA BASORUN MFB", "MFB", "Micro-Finance Banks"),
        new("OROKAM MFB", "MFB", "Micro-Finance Banks"),
        new("ORSU MFB", "MFB", "Micro-Finance Banks"),
        new("OSANTA MFB", "MFB", "Micro-Finance Banks"),
        new("OSCT MFB", "MFB", "Micro-Finance Banks"),
        new("OSI MFB", "MFB", "Micro-Finance Banks"),
        new("OSOMHE MFB", "MFB", "Micro-Finance Banks"),
        new("OSPOLY MFB", "MFB", "Micro-Finance Banks"),
        new("OSUMENYI MFB", "MFB", "Micro-Finance Banks"),
        new("OTUO MFB", "MFB", "Micro-Finance Banks"),
        new("OURS MFB", "MFB", "Micro-Finance Banks"),
        new("OWOTUTU MFB", "MFB", "Micro-Finance Banks"),
        new("OYAN MFB", "MFB", "Micro-Finance Banks"),
        new("OYE VERSITY MICROFINANCE BANK LIMITED", "MFB", "Micro-Finance Banks"),
        new("PACT MICROFINANCE BANK", "MFB", "Micro-Finance Banks"),
        new("PALMCOAST MFB", "MFB", "Micro-Finance Banks"),
        new("PALMERA MFB", "MFB", "Micro-Finance Banks"),
        new("PANA MFB", "MFB", "Micro-Finance Banks"),
        new("PARKWAY MFB", "MFB", "Micro-Finance Banks"),
        new("PATHFINDER MFB", "MFB", "Micro-Finance Banks"),
        new("PATRICKGOLD MFB", "MFB", "Micro-Finance Banks"),
        new("PEACE MFB", "MFB", "Micro-Finance Banks"),
        new("PECAN TRUST MFB", "MFB", "Micro-Finance Banks"),
        new("PENINSULA MFB LTD", "MFB", "Micro-Finance Banks"),
        new("PENNYWISE MFB", "MFB", "Micro-Finance Banks"),
        new("PENTECOST MFB LTD", "MFB", "Micro-Finance Banks"),
        new("PERSONAL TRUST MFB", "MFB", "Micro-Finance Banks"),
        new("PETRA MFB", "MFB", "Micro-Finance Banks"),
        new("PHOENIX MFB", "MFB", "Micro-Finance Banks"),
        new("PILLAR MFB", "MFB", "Micro-Finance Banks"),
        new("Pointone Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("POLYBADAN MFB", "MFB", "Micro-Finance Banks"),
        new("POLYUNWANNA MFB", "MFB", "Micro-Finance Banks"),
        new("PREEMINENT MFB", "MFB", "Micro-Finance Banks"),
        new("PRESTIGE MFB", "MFB", "Micro-Finance Banks"),
        new("PRISCO MFB", "MFB", "Micro-Finance Banks"),
        new("PRISTINE DIVITIS MFB", "MFB", "Micro-Finance Banks"),
        new("PROJECTS MFB", "MFB", "Micro-Finance Banks"),
        new("PROSPECTS MFB", "MFB", "Micro-Finance Banks"),
        new("PROSPERITY MFB", "MFB", "Micro-Finance Banks"),
        new("PRUDENT MFB", "MFB", "Micro-Finance Banks"),
        new("PYRAMID MFB", "MFB", "Micro-Finance Banks"),
        new("QUBE MFB", "MFB", "Micro-Finance Banks"),
        new("QUICKFUND MFB", "MFB", "Micro-Finance Banks"),
        new("RAHAMA MFB", "MFB", "Micro-Finance Banks"),
        new("RAKIB MFB", "MFB", "Micro-Finance Banks"),
        new("RAMILOWO MFB", "MFB", "Micro-Finance Banks"),
        new("RANDALPHA", "MFB", "Micro-Finance Banks"),
        new("RANO MFB", "MFB", "Micro-Finance Banks"),
        new("REFINED BENEFITS MFB", "MFB", "Micro-Finance Banks"),
        new("REGENT MFB", "MFB", "Micro-Finance Banks"),
        new("REHOBOTH MFB", "MFB", "Micro-Finance Banks"),
        new("RELIANCE MFB", "MFB", "Micro-Finance Banks"),
        new("RENMONEY MFB", "MFB", "Micro-Finance Banks"),
        new("REPHIDIM MFB", "MFB", "Micro-Finance Banks"),
        new("RIC MFB", "MFB", "Micro-Finance Banks"),
        new("RICHWAY MFB LTD.", "MFB", "Micro-Finance Banks"),
        new("RIGO MFB", "MFB", "Micro-Finance Banks"),
        new("RIMA GROWTH PATHWAY MFB LTD", "MFB", "Micro-Finance Banks"),
        new("RIMA MFB", "MFB", "Micro-Finance Banks"),
        new("RIMIN GADO MFB", "MFB", "Micro-Finance Banks"),
        new("RIVERSIDE MFB", "MFB", "Micro-Finance Banks"),
        new("ROCKSHIELD MFB", "MFB", "Micro-Finance Banks"),
        new("ROLEZ MFB", "MFB", "Micro-Finance Banks"),
        new("ROYAL BLUE MFB", "MFB", "Micro-Finance Banks"),
        new("ROYAL EXCHANGE MFB", "MFB", "Micro-Finance Banks"),
        new("ROYAL LIFE KEY MFB", "MFB", "Micro-Finance Banks"),
        new("ROYAL MFB", "MFB", "Micro-Finance Banks"),
        new("RUBIES MFB", "MFB", "Micro-Finance Banks"),
        new("SABI MFB", "MFB", "Micro-Finance Banks"),
        new("SABON YELWA MFB", "MFB", "Micro-Finance Banks"),
        new("SABUWA MFB LTD", "MFB", "Micro-Finance Banks"),
        new("SAFANA MFB", "MFB", "Micro-Finance Banks"),
        new("SAFE HAVEN MFB", "MFB", "Micro-Finance Banks"),
        new("SAFEGATE MFB", "MFB", "Micro-Finance Banks"),
        new("SAFELINE MFB", "MFB", "Micro-Finance Banks"),
        new("SAGAMU MFB", "MFB", "Micro-Finance Banks"),
        new("SANDAMU MFB", "MFB", "Micro-Finance Banks"),
        new("SAPIDA MFB", "MFB", "Micro-Finance Banks"),
        new("SARKIN KUDU MFB LTD", "MFB", "Micro-Finance Banks"),
        new("SEAL MICROFINANCE BANK LIMITED", "MFB", "Micro-Finance Banks"),
        new("SEAP MFB", "MFB", "Micro-Finance Banks"),
        new("SEEDVEST MFB", "MFB", "Micro-Finance Banks"),
        new("SENCHI MFB", "MFB", "Micro-Finance Banks"),
        new("Shalom MFB", "MFB", "Micro-Finance Banks"),
        new("SHANONO MFB", "MFB", "Micro-Finance Banks"),
        new("SHEPHERD TRUST MFB", "MFB", "Micro-Finance Banks"),
        new("SHIELD MFB", "MFB", "Micro-Finance Banks"),
        new("SHONGOM MFB", "MFB", "Micro-Finance Banks"),
        new("SINCERE MFB", "MFB", "Micro-Finance Banks"),
        new("SLS MFB", "MFB", "Micro-Finance Banks"),
        new("SMARTMICRO MFB", "MFB", "Micro-Finance Banks"),
        new("SNOW MFB", "MFB", "Micro-Finance Banks"),
        new("SOLID ALLIANZ MFB", "MFB", "Micro-Finance Banks"),
        new("SOLID ROCK MFB", "MFB", "Micro-Finance Banks"),
        new("Solid Trust MFB", "MFB", "Micro-Finance Banks"),
        new("SOROMAN MFB", "MFB", "Micro-Finance Banks"),
        new("SOURCE MICROFINANCE BANK LIMITED", "MFB", "Micro-Finance Banks"),
        new("SPARKLE MFB", "MFB", "Micro-Finance Banks"),
        new("SPECTRUM MFB", "MFB", "Micro-Finance Banks"),
        new("STANDARD MFB", "MFB", "Micro-Finance Banks"),
        new("STANFORD MFB", "MFB", "Micro-Finance Banks"),
        new("STATESIDE MFB", "MFB", "Micro-Finance Banks"),
        new("STELLAS MFB", "MFB", "Micro-Finance Banks"),
        new("STEP BY STEP MFB", "MFB", "Micro-Finance Banks"),
        new("STILLWATERS MFB LTD", "MFB", "Micro-Finance Banks"),
        new("STOCKCORP MFB", "MFB", "Micro-Finance Banks"),
        new("SULSPAP MFB", "MFB", "Micro-Finance Banks"),
        new("SUMAILA MFB", "MFB", "Micro-Finance Banks"),
        new("SUNBEAM MFB", "MFB", "Micro-Finance Banks"),
        new("Suntop Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("SUPPORT MFB", "MFB", "Micro-Finance Banks"),
        new("SUPREME MFB", "MFB", "Micro-Finance Banks"),
        new("SURE ANCHOR MFB", "MFB", "Micro-Finance Banks"),
        new("TANADI MFB", "MFB", "Micro-Finance Banks"),
        new("TANGALE MFB", "MFB", "Micro-Finance Banks"),
        new("Tangerine Money Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("TASUED MFB", "MFB", "Micro-Finance Banks"),
        new("TCF MFB", "MFB", "Micro-Finance Banks"),
        new("TEERUS MICROFINANCE BANK LIMITED", "MFB", "Micro-Finance Banks"),
        new("TF MFB", "MFB", "Micro-Finance Banks"),
        new("The Millennium MFB", "MFB", "Micro-Finance Banks"),
        new("TOFA MFB", "MFB", "Micro-Finance Banks"),
        new("TOP RATE MFB", "MFB", "Micro-Finance Banks"),
        new("TOPCLASS MFB", "MFB", "Micro-Finance Banks"),
        new("TOTAL TRUST MFB", "MFB", "Micro-Finance Banks"),
        new("TOUCHGOLD MFB", "MFB", "Micro-Finance Banks"),
        new("TOWNSERVE MFB", "MFB", "Micro-Finance Banks"),
        new("TREASURES MFB", "MFB", "Micro-Finance Banks"),
        new("TRIDENT MFB", "MFB", "Micro-Finance Banks"),
        new("TRIPPLE A MFB", "MFB", "Micro-Finance Banks"),
        new("TRIUMPHANT MICROFINANCE BANK LIMITED", "MFB", "Micro-Finance Banks"),
        new("TRUST MFB", "MFB", "Micro-Finance Banks"),
        new("TRUSTBANC J6", "MFB", "Micro-Finance Banks"),
        new("TRUSTFUND MFB", "MFB", "Micro-Finance Banks"),
        new("TSANYAWA MFB", "MFB", "Micro-Finance Banks"),
        new("TUDUNWADA MFB LTD", "MFB", "Micro-Finance Banks"),
        new("U & C MFB", "MFB", "Micro-Finance Banks"),
        new("UCB MFB", "MFB", "Micro-Finance Banks"),
        new("UDA MFB", "MFB", "Micro-Finance Banks"),
        new("UDOKA MFB", "MFB", "Micro-Finance Banks"),
        new("UGA MFB", "MFB", "Micro-Finance Banks"),
        new("UGBORIMILI MFB", "MFB", "Micro-Finance Banks"),
        new("UHURU MFB", "MFB", "Micro-Finance Banks"),
        new("UKPOR MFB", "MFB", "Micro-Finance Banks"),
        new("UKWALA MFB", "MFB", "Micro-Finance Banks"),
        new("ULTIMATE MFB", "MFB", "Micro-Finance Banks"),
        new("UMMAH MFB", "MFB", "Micro-Finance Banks"),
        new("UMUAWULU MFB", "MFB", "Micro-Finance Banks"),
        new("UMUCHINEMERE PROCREDIT MFB", "MFB", "Micro-Finance Banks"),
        new("UMUCHUKWU MFB", "MFB", "Micro-Finance Banks"),
        new("UMUNNACHI MFB", "MFB", "Micro-Finance Banks"),
        new("UMUOJI MFB", "MFB", "Micro-Finance Banks"),
        new("UMYU Microfinance Bank Limited", "MFB", "Micro-Finance Banks"),
        new("UNAAB MFB", "MFB", "Micro-Finance Banks"),
        new("UNGOGO MFB", "MFB", "Micro-Finance Banks"),
        new("UNIBADAN MFB", "MFB", "Micro-Finance Banks"),
        new("UNICAL MFB", "MFB", "Micro-Finance Banks"),
        new("UNIFUND MFB", "MFB", "Micro-Finance Banks"),
        new("UNILAG MFB LTD", "MFB", "Micro-Finance Banks"),
        new("UNILORIN MFB", "MFB", "Micro-Finance Banks"),
        new("UNIMAID MFB", "MFB", "Micro-Finance Banks"),
        new("UNITED CAPITAL MFB", "MFB", "Micro-Finance Banks"),
        new("UNIUYO MFB", "MFB", "Micro-Finance Banks"),
        new("UNIVERSITY OF BENIN MFB", "MFB", "Micro-Finance Banks"),
        new("UNN MFB", "MFB", "Micro-Finance Banks"),
        new("UNUBI MFB", "MFB", "Micro-Finance Banks"),
        new("URBAN MFB", "MFB", "Micro-Finance Banks"),
        new("URE MFB", "MFB", "Micro-Finance Banks"),
        new("UTAKO MFB", "MFB", "Micro-Finance Banks"),
        new("UTUH MFB", "MFB", "Micro-Finance Banks"),
        new("UVUOMA MFB", "MFB", "Micro-Finance Banks"),
        new("UVURU MFB", "MFB", "Micro-Finance Banks"),
        new("UZONDU MFB", "MFB", "Micro-Finance Banks"),
        new("VCL MFB", "MFB", "Micro-Finance Banks"),
        new("VFD MFB LTD", "MFB", "Micro-Finance Banks"),
        new("VICTORY MFB", "MFB", "Micro-Finance Banks"),
        new("VISA MFB", "MFB", "Micro-Finance Banks"),
        new("VISCOUNT MFB", "MFB", "Micro-Finance Banks"),
        new("WAILA MFB", "MFB", "Micro-Finance Banks"),
        new("Wallet Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("WAYA MFB", "MFB", "Micro-Finance Banks"),
        new("WE MICROFINANCE BANK LIMITED", "MFB", "Micro-Finance Banks"),
        new("WELFARE MFB", "MFB", "Micro-Finance Banks"),
        new("WETLAND MFB", "MFB", "Micro-Finance Banks"),
        new("WOLIWO MFB", "MFB", "Micro-Finance Banks"),
        new("WOMEN DEVELOPMENT MFB", "MFB", "Micro-Finance Banks"),
        new("WRA MFB", "MFB", "Micro-Finance Banks"),
        new("WUDIL MFB", "MFB", "Micro-Finance Banks"),
        new("XSLNCE MFB", "MFB", "Micro-Finance Banks"),
        new("YABO MFB", "MFB", "Micro-Finance Banks"),
        new("Yankari MFB", "MFB", "Micro-Finance Banks"),
        new("YAURI EMIRATES MFB", "MFB", "Micro-Finance Banks"),
        new("YCT Microfinance Bank", "MFB", "Micro-Finance Banks"),
        new("YENENG MFB", "MFB", "Micro-Finance Banks"),
        new("YES MFB", "MFB", "Micro-Finance Banks"),
        new("YOBE STATE MFB", "MFB", "Micro-Finance Banks"),
        new("ZAFEC MFB LTD", "MFB", "Micro-Finance Banks"),
        new("ZAZZAU MFB", "MFB", "Micro-Finance Banks"),
        new("ZEFA MFB", "MFB", "Micro-Finance Banks"),
        new("ZIKORA MFB", "MFB", "Micro-Finance Banks"),
        new("ZION MFB", "MFB", "Micro-Finance Banks"),
        new("ZURMI MFB", "MFB", "Micro-Finance Banks"),
        new("ZURU MFB", "MFB", "Micro-Finance Banks"),

        // Mobile Money Operators (17)
        new("ABEG TECHNOLOGIES LIMITED", "MMO", "Mobile Money Operators"),
        new("CHAMS MOBILE LIMITED", "MMO", "Mobile Money Operators"),
        new("ETRANZACT INTERNATIONAL LIMITED", "MMO", "Mobile Money Operators"),
        new("FORTIS MOBILE MONEY LIMITED", "MMO", "Mobile Money Operators"),
        new("FUNDS AND ELECTRONIC TRANSFER (FETS) LIMITED", "MMO", "Mobile Money Operators"),
        new("HEDONMARK MANAGEMENT SERVICES LIMITED", "MMO", "Mobile Money Operators"),
        new("KONGAPAY TECHNOLOGIES LIMITED (FORMERLY ZINTERNET LIMITED )", "MMO", "Mobile Money Operators"),
        new("MKUDI LIMITED", "MMO", "Mobile Money Operators"),
        new("NOWNOW DIGITAL SYSTEMS LIMITED (FORMERLY CONTEC GLOBAL INFOTECH LIMITED)", "MMO", "Mobile Money Operators"),
        new("OPAY DIGITAL SERVICES LIMITED (FORMERLY PAYCOM NIGERIA LIMITED)", "MMO", "Mobile Money Operators"),
        new("PAGATECH LIMITED", "MMO", "Mobile Money Operators"),
        new("PALMPAY LIMITED", "MMO", "Mobile Money Operators"),
        new("PARKWAY PROJECTS LIMITED", "MMO", "Mobile Money Operators"),
        new("TEASY INTERNATIONAL COMPANY LTD.", "MMO", "Mobile Money Operators"),
        new("VISUAL ICT LIMITED", "MMO", "Mobile Money Operators"),
        new("VTNETWORK LIMITED", "MMO", "Mobile Money Operators"),
        new("XPRESS MTS LIMITED", "MMO", "Mobile Money Operators"),

        // Non-Interest Banks (5)
        new("Alternative Bank Limited", "NIB", "Non-Interest Banks"),
        new("JAIZ BANK PLC", "NIB", "Non-Interest Banks"),
        new("LOTUS BANK LTD", "NIB", "Non-Interest Banks"),
        new("Summit Bank Limited", "NIB", "Non-Interest Banks"),
        new("TAJ", "NIB", "Non-Interest Banks"),

        // Primary Mortgage Institutions (33)
        new("ABBEY MORTGAGE BANK", "PMB", "Primary Mortgage Institutions"),
        new("Adamawa Mortgage Bank Limited", "PMB", "Primary Mortgage Institutions"),
        new("AG HOMES", "PMB", "Primary Mortgage Institutions"),
        new("AKWA SAVINGS", "PMB", "Primary Mortgage Institutions"),
        new("ASO SAVINGS & LOANS", "PMB", "Primary Mortgage Institutions"),
        new("BRENT (SKYFIELD) SAVINGS", "PMB", "Primary Mortgage Institutions"),
        new("CENTAGE SAVINGS & LOANS", "PMB", "Primary Mortgage Institutions"),
        new("CITY CODE", "PMB", "Primary Mortgage Institutions"),
        new("COOP SAVINGS & LOANS", "PMB", "Primary Mortgage Institutions"),
        new("DELTA MORTGAGE FINANCE", "PMB", "Primary Mortgage Institutions"),
        new("FBN MORTGAGES", "PMB", "Primary Mortgage Institutions"),
        new("FHA HOMES LTD.", "PMB", "Primary Mortgage Institutions"),
        new("FIRST GENERATION HOMES", "PMB", "Primary Mortgage Institutions"),
        new("GATEWAY SAVINGS", "PMB", "Primary Mortgage Institutions"),
        new("GLOBAL TRUST", "PMB", "Primary Mortgage Institutions"),
        new("HAGGAI MORTGAGE BANK", "PMB", "Primary Mortgage Institutions"),
        new("HOME-BASE MORTGAGE", "PMB", "Primary Mortgage Institutions"),
        new("IMPERIAL HOMES", "PMB", "Primary Mortgage Institutions"),
        new("INFINITY TRUST", "PMB", "Primary Mortgage Institutions"),
        new("JIGAWA SAVINGS & LOANS", "PMB", "Primary Mortgage Institutions"),
        new("JUBILEE-LIFE MORTGAGE BANK", "PMB", "Primary Mortgage Institutions"),
        new("KEBBI STATE HOMES", "PMB", "Primary Mortgage Institutions"),
        new("LAGOS BUILDING & INVESTMENT", "PMB", "Primary Mortgage Institutions"),
        new("MAYFRESH MORTGAGE BANK", "PMB", "Primary Mortgage Institutions"),
        new("MGSL MORTGAGE BANK", "PMB", "Primary Mortgage Institutions"),
        new("MUTUAL ALLIANCE", "PMB", "Primary Mortgage Institutions"),
        new("NEW PRUDENTIAL", "PMB", "Primary Mortgage Institutions"),
        new("NIGERIA POLICE MORTGAGE BANK", "PMB", "Primary Mortgage Institutions"),
        new("OMOLUABI (LIVINGSPRING)", "PMB", "Primary Mortgage Institutions"),
        new("PLATINUM MORTGAGE BANK", "PMB", "Primary Mortgage Institutions"),
        new("REFUGE HOMES", "PMB", "Primary Mortgage Institutions"),
        new("STB BUILDING SOCIETY", "PMB", "Primary Mortgage Institutions"),
        new("TRUSTBOND MORTGAGE BANK", "PMB", "Primary Mortgage Institutions"),

        // Payment Service Banks (5)
        new("9 PSB Ltd", "PSB", "Payment Service Banks"),
        new("Hope PSB Ltd", "PSB", "Payment Service Banks"),
        new("MOMO PAYMENT SERVICE BANK", "PSB", "Payment Service Banks"),
        new("Moneymaster PSB Ltd", "PSB", "Payment Service Banks"),
        new("SMARTCASH PSB LIMITED", "PSB", "Payment Service Banks"),

    ];

    /// <summary>All 978 CBN-licensed institutions.</summary>
    public static IReadOnlyList<CbnInstitutionEntry> All => _all;

    /// <summary>
    /// Search institutions by name. Returns prefix matches first, then substring matches.
    /// </summary>
    public static IReadOnlyList<CbnInstitutionEntry> Search(string query, string? categoryCode = null, int limit = 15)
    {
        if (string.IsNullOrWhiteSpace(query) || query.Length < 2)
            return Array.Empty<CbnInstitutionEntry>();

        var q = query.Trim();
        var source = string.IsNullOrWhiteSpace(categoryCode)
            ? _all.AsEnumerable()
            : _all.Where(x => x.CategoryCode.Equals(categoryCode, StringComparison.OrdinalIgnoreCase));

        var prefixMatches = new List<CbnInstitutionEntry>();
        var containsMatches = new List<CbnInstitutionEntry>();

        foreach (var entry in source)
        {
            if (entry.Name.StartsWith(q, StringComparison.OrdinalIgnoreCase))
                prefixMatches.Add(entry);
            else if (entry.Name.Contains(q, StringComparison.OrdinalIgnoreCase))
                containsMatches.Add(entry);
        }

        var results = new List<CbnInstitutionEntry>(prefixMatches.Count + containsMatches.Count);
        results.AddRange(prefixMatches);
        results.AddRange(containsMatches);
        return results;
    }

    /// <summary>Get total match count for "N more" indicator.</summary>
    public static int CountMatches(string query, string? categoryCode = null)
    {
        if (string.IsNullOrWhiteSpace(query) || query.Length < 2)
            return 0;

        var q = query.Trim();
        var source = string.IsNullOrWhiteSpace(categoryCode)
            ? _all.AsEnumerable()
            : _all.Where(x => x.CategoryCode.Equals(categoryCode, StringComparison.OrdinalIgnoreCase));

        return source.Count(x => x.Name.Contains(q, StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>Get all institutions in a category.</summary>
    public static IReadOnlyList<CbnInstitutionEntry> GetByCategory(string categoryCode)
    {
        return _all.Where(x => x.CategoryCode.Equals(categoryCode, StringComparison.OrdinalIgnoreCase)).ToList();
    }
}

public sealed record CbnInstitutionEntry(string Name, string CategoryCode, string CategoryLabel);
