// <auto-generated />
using FC.Engine.Infrastructure.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FC.Engine.Infrastructure.Migrations
{
    [DbContext(typeof(MetadataDbContext))]
    [Migration("20260315120001_AddRegulatorIqExaminationFields")]
    partial class AddRegulatorIqExaminationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Full target model is maintained in MetadataDbContextModelSnapshot.
            // This file exists solely to register the migration ID with EF Core so that
            // dotnet-ef database update applies the migration and dotnet-ef migrations list
            // shows it in the correct sequence position (after 20260315120000_AddAuditLogEntityRef).
        }
    }
}
